name: ci
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis:6.0
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Test
        run: poetry run pytest --redis-connection-string redis://redis:6379
